### ISSUE TITLE
Failed to build kui docker image with wiki guide on macOS (AssertionError [ERR_ASSERTION]: rimraf: missing path)

### ISSUE THREAD

**Issue by xiaoshimimi** [kubernetes-sigs/kui#7639] opened 2021-06-16 03:21 UTC
**Describe the bug**
I'm trying to build kui docker image with this guide: https://github.com/kubernetes-sigs/kui/wiki/4.-Building-for-Production#scripts-to-aid-in-building-a-hosted-kui

But failed finally with some error.

**Steps to reproduce the behavior**

1. `git clone git://github.com/IBM/kui.git`
2. `cd kui`
3. `npm ci`
4. `INJECT_KUBECONFIG=true npx kui-build-docker-with-proxy`
5. see error:

![image](https://user-images.githubusercontent.com/5269532/122153032-c295a200-ce94-11eb-9792-d4fb45f17bf4.png)

**Expected behavior**
does not get error with `npx kui-build-docker-with-proxy` command

**System**

- Kui version: `master branch`
- Operating system: `macOS`

**Comment by starpit** [comment] 2021-06-16 13:52
thanks! i know of at least one recent regression due to the switch from node-pty-prebuilt-multiarch to node-pty. Fixing that. I'm not sure if this explains your error, but the docker-proxy build definitely is broken at the moment.

**Comment by starpit** [comment] 2021-06-16 13:58
The errors you have shown in the screenshot seem different. They are failures during `npm ci`. I'm not sure what about Kui would cause `npm ci` to fail. I'm going to assume that the errors above are a side-effect of the underlying build failure, for now. Once the PR has been merged, please re-test. thanks!

**Closed** 2021-06-16 14:28 UTC
