### ISSUE TITLE
Distributing kui plugins via krew

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/kui#2962] opened 2019-10-10 21:42 UTC
**Describe the topic**
Distributing kui plugins via krew.

This topic was discussed twice during SIG-CLI meetings with a small demo on Oct 9.

Kui plugins should be lightweight in that not every UI plugin installs its own electron/chromium dependencies. For that they need some dependency management on the kui side. The idea is to have a helper (?`kask`?) which takes care of providing runtime dependencies for UI plugins.
The plugins themselves can then be rather slim and install just the bundle of `node_modules` and program logic. (please correct me, if I got something wrong here).

Kui developers raised the idea that those plugins could be distributed via `krew`. So let's talk about what are the requirements that kui has for plugin management. This will help krew understand what would be needed to support this use-case. Also, there may be some easy steps to be taken by krew to unblock further development on kui side.

**Comment by corneliusweig** [comment] 2019-10-10 21:43
So first off, can you share any documents that will help to better understand the requirements?

**Comment by starpit** [comment] 2019-10-15 00:19
hi @corneliusweig thanks for the feedback on the SIG CLI call, and here as well!

here is the current thinking:

1) very small go library/binary that acquires the base Kui platform. this is essentially a slim Kui client, and we can decide on what kind of theming and branding we want (i.e. icons, color schemes, etc.) for this client. we have been nicknaming this go binary `kask`.

2) `kask` can also serve as a command delegator; e.g. on UNIX-oriented platforms, via the standard symlink-orientation trick (whereby a named symlink alters the behavior of a single binary), we can have e.g. `kubectl-myplugin` act as a delegate to commands hosted by that plugin

3) the kui monorepo includes a "plugin-manager" plugin; we are including this in the current base Kui client. thus, `kask` can also serve to install Kui plugins, via either `kask plugin install myplugin`, or, via the `kubectl-kask` symlink trick, via `kubectl kask install myplugin`, etc.

4) user then installs some plugins; the plugin manager can optionally generate the `kubectl-myplugin` delegate, and, when operating under the direction of `kask` will do so by default.

i'll keep expanding on this. but i wanted to respond to you. sorry for the delay in this initial response! thanks again for the feedback, it is very much appreciated.

**Comment by corneliusweig** [comment] 2019-10-15 07:14
Hi @starpit, no worries about slow response. I'm also quite slow these days :)

I'm still trying to understand how `krew` fits into the picture. Also I'm not entirely sure about what of the above has already been decided, or is just an option that could be followed.

For `krew` integration, I see three possibilities:

1. `kask`/`kui` as plugins distributed via `krew`. In that case, UI plugins are fully managed by the `kui` tools and `krew`s job is over after installing a plugin.
2. A mixed solution, where the user needs to install `kask` first, and then she can install UI plugins via `krew`. Those plugins would still use `kask` under the hood.
3. `kask` being fully integrated into `krew` (as suggested in point 6 above).

---

For option 3, it is too early to discuss this IMHO, as we know too little about feasibility and UI adoption.

Option 2 requires handling a lot of special cases on `krew`s side. First, `krew` does not handle dependencies whatsoever. It's therefore impossible to automatically install `kask` if a user installs some UI plugin (and hasn't installed `kask` beforehand). Second, krew can only create exactly one symlink to a single target from the plugin archive. It is therefore unclear, how `krew` should support the command delegator pattern (point 2 in the above post).

Lastly, option 1 cleanly separates the concerns of UI plugins and CLI plugins. It will also allow to develop the functionality of `kask` and `krew` independently. At this stage, this seems to be the cleanest approach to me, as most UI plugin logic has to be handled by `kask` anyway.

WDYT?

**Comment by starpit** [comment] 2019-10-22 13:27
i think option 1 sounds good! here is the current state of things:

![Screen Shot 2019-10-22 at 9 27 22 AM](https://user-images.githubusercontent.com/4741620/67290509-2f814a80-f4ae-11e9-972b-353e7c8cca1b.png)

where, after the last command, a window pops up

**Comment by starpit** [comment] 2019-10-22 13:33
this includes:

1) kask will not pop up a window for plugin management operations, as shown in the screenshot
2) kask+kui, on plugin installation, will create a `kubectl-foo` delegate that knows how to hand off control (this is just a symlink to kask; and kask itself recognizes that it was invoked in kubectl-foo fashion, etc.)

right now, kask uses ~/.kask/bin to store the delegates; i could shift this to be ~/.krew/bin?

**Comment by corneliusweig** [comment] 2019-10-22 19:30
Meeting notes of conference call
---

Attendees: @starpit @paulcastro @ahmetb @corneliusweig 

The agenda of this meeting was to get feedback on the current approach and discuss feasible integration methods into `krew`. Two options were recommended by Ahmet:

### Fat bundles

For this option, UI plugins would be distributed as fat bundles, each including their own instance of Electron. This will make UI plugins rather large (>100MB), but there are various platforms to host such big archives for open source projects. In addition, the number of UI plugins will be limited for the near future, so that the duplicated downloads would not matter that much (the underlying assumption is that only larger organizations will invest in developing a UI plugin). This will allow KUI plugins to directly make use of `krew`s installation and upgrade machinery.
As stated by Nick, this approach would work today without any further work on KUI side. Likewise, it would work for krew, as long as the plugins have a single entry point executable.

From `krew`s perspective, this is the simplest approach and allows to release UI plugins with the least overhead. This will therefore be the fastest way to collect user feedback for UI plugins.

### Thin bundles with KUI base plugin

The idea of this option is to have a base plugin which includes Electron and other KUI base dependencies. This base plugin acts as a shell to execute thin UI plugins which have to be installed independently via krew. These thin plugin bundles need to include a helper program which checks for the existence of the KUI base plugin. When missing, the helper should exit with a recommendation to install the base plugin. When present, the helper calls the base plugin and initiates the execution of the UI code inside the UI shell from the base plugin.
The main advantage is that Electron needs to be distributed only once as part of the base plugin, so that UI plugins become much smaller. On the downside, UI plugins can only use one version of Electron (the one from the base plugin). Maybe this can be handled by a smarter base plugin which can manage different Electron versions simultaneously.
For managing and upgrading thin UI plugins, `krew` can be used as-is. As far as I understand, parts of `kask` could be used to build such a base plugin.

**Comment by starpit** [comment] 2019-10-22 19:38
thanks for capturing these notes. 

i agree with the two summaries.

an (i think?) minor variant of the "thin bundles" approach would let plugin developers make the choice, e.g. whether the BIN is an electron app versus `kask/kui-helper`.  if the developer chooses the latter, then `kask`, on first run, can acquire the base bundles.

that is, we can make `kask` transparent to the users, except as manifested by a "please wait while we complete the installation" one-time message.

**Comment by corneliusweig** [comment] 2019-10-22 19:44
That means however, that the transparent `kask` is not managed by `krew` and would therefore not benefit from its install/upgrade mechanisms, right?

Besides, there needs to be a fixed location where `kask` installs Electron. When distributed via `krew` that answer is easy, but what if Electron is installed transparently? Is there a natural place in that case?

**Comment by starpit** [comment] 2019-10-22 20:09
kask itself would be under the management of krew. the chain-installed kui-base would not be under krew's management, but rather managed by kask. 

it is a trade-off we can explore. i want to keep the discussion open, for now, because there are foreseeable (but possibly ignoreable) issues with having one chromium per plugin; e.g. now every plugin launch will add a separate icon to the macOS dock

**Comment by ahmetb** [comment] 2019-10-22 20:12
I recommend moving away from the notion of "kask".

The "thin bundle" model it would work as follows:

- Have a `kubectl kui-base` plugin distributed and updated via krew. This plugin contains electron and other parts of kui runtime.
- Allow kui plugin devs to create plugin bundles using a single command (`npm krew-bundle`)
- This command would create a tarball bundle that contains a cross platform entrypoint program.
- Plugin devs can use this entrypoint program as the plugin executable in krew manifest (e.g. `bin: foo_darwin`, `bin: foo_linux`, `bin: foo_windows.exe`) **All kui plugin tarballs will have these binaries** most probably.
- Tarball is then distributed as a krew plugin, installed by user directly with krew.
- entrypoint program would detect if `kubectl-kui_base` is in PATH (if not, fails in terminal with error message: Please run "kubectl krew install kui-base")
- entrypoint program would launch `kui-base` with the path to kui plugin bundle containing other assets)
- `kubectl-kui_base` launches `electron` with the plugin assets directory.


> every plugin launch would add a separate icon to the macOS dock

I think this is expected behavior. I would rather have separate programs have separate lifecycles/fate and Dock icons.

**Comment by corneliusweig** [comment] 2019-10-24 20:12
I'm not sure if I follow correctly. Your argument only holds when users switch between different UI plugins while leaving at least one UI window open, is that correct?
However, I think that most workflows would remain in the scope of a single UI plugin, so that startup times are already amortized pretty well, if each plugin has to start its own Chromium.

As to cluttering the dock: it's hard to say how many UI plugins will be there eventually. This is best decided by practice and see how many people contribute a UI plugin. Why not start with a simple approach and iterate from there, if it becomes a problem?

**Comment by ahmetb** [comment] 2019-10-24 22:10
I agree with Cornelius here.
Our suggestions based on given the resources you/we have.
This is open source, so everyone operates on limited amount of time and resources.

Given there are practically no KUI plugins today (and there won't be 10 probably anytime soon, let alone users don't even know KUI yet), I would say you are optimizing this waaaaay too early.

I wanted to reiterate from our meeting: Let's try to get it to work with minimum effort before you start optimizing.

To get there, follow one of the suggestions above, such as "fat bundles" and let's see if we can get any user to work with it. After you get user feedback, you can iterate.

Otherwise, I'm afraid you're going down a path of optimizing things with a lot of code, and introducing new projects along the way that you might have trouble finding people to maintain long-term. My advice is to stick to the simplest working solution –you'll be surprised how far it will get you.

**Comment by starpit** [comment] 2019-10-24 23:43
hey all, so as not to derail the most important short-term topics, i will table the larger discussions of "fat versus thin" plugins for a later date.

we have made some progress on the "kubeui" plugin repo. this is mostly an externalized form of the plugin that is in the monorepo. kui has had support for this style of external clients for a while now, so it wasn't much work to reformulate the monorepo plugin into an external one. 

a bit more work is needed, including ensuring that the tests all run correctly, writing a krew manifest, and filling in a few other gaps in the implementation. but it's getting pretty close: https://github.com/kui-shell/plugin-kubeui

**Comment by starpit** [comment] 2019-11-08 17:23
update: the kubeui plugin now has a release that (for now, at least) can be installed as a kubectl plugin via `curl | tar zxf`: https://github.com/kui-shell/plugin-kubeui/releases/latest/

**Comment by ahmetb** [comment] 2020-06-15 17:24
> An update that on Mac, you’ll soon be able to install the kubectl plugin via Homebrew.

Do you mind elaborating @LouisStAmour? I think you already can?

**Comment by LouisStAmour** [comment] 2020-06-15 17:28
> > An update that on Mac, you’ll soon be able to install the kubectl plugin via Homebrew.
> 
> Do you mind elaborating @LouisStAmour? I think you already can?

Sure, right now it installs just the app and you have to manually symlink the kubectl-kui script to /usr/local/bin or another part of your path. With the PR just merged for moving the script inside the .app, future updates of the script just require installing a new copy of the app on macOS.

Still to do is update Homebrew to add the binary symlink automatically. Once that’s done, no additional manual steps on Mac would be required, no curl either, just “brew cask install kui” and “kubectl kui get pods” will do what you expect from a clean install.

**Comment by LouisStAmour** [comment] 2020-06-22 05:19
Just a quick note that on Mac, `brew cask install kui` now also installs the kubectl plugin. It seemed more natural that Homebrew should install both the Kui.app to /Applications and install a symlink for `kubectl-kui` to launch the app as a kubectl plugin.

**Comment by uocxp** [comment] 2020-09-28 13:49
any updates ?

**Closed** 2021-05-23 11:43 UTC
Labels: lifecycle/rotten
