### ISSUE TITLE
kubectl get vs does not work

### ISSUE THREAD

**Issue by houshym** [kubernetes-sigs/kui#7301] opened 2021-04-09 20:49 UTC
**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version:
- Operating system:

**Comment by starpit** [comment] 2021-05-18 18:36
Probably a duplicate of #7387

**Closed by starpit** 2021-05-18 18:36 UTC
