### ISSUE TITLE
Environment variables should be inherited afresh each time I do `kui shell`

### ISSUE THREAD

**Issue by sriumcp** [kubernetes-sigs/kui#1470] opened 2019-05-23 20:39 UTC
1. I type `kui shell` for the first time on my terminal, and kui starts and inherits all the environment variables defined at that point in time
2. I close the kui window, go back to the terminal and create a new environment variable by `export FOO=BAR`
3. I reopen the kui window by typing `kui shell`. This time, it *does not* inherit the variable FOO
4. If go to my dock, and quit kui, and then retype `kui shell` in the terminal, it picks up the environment variable FOO

Desired feature: It would good not to have to quit `kui` in 4. above. When I type `kui shell`, the kui window that comes up needs to pickup the environment variables at that point in time

**Comment by starpit** [comment] 2019-05-23 22:58
i see, thanks for this report. i believe what is happening here is that the main electron process stays up  after you close all kui windows. this seems to be a regression, as it is not the intended behavior.

**Comment by starpit** [comment] 2019-05-23 23:02
ah, i see. this is not a regression, i was thinking of work from another branch that never got merged. thanks again for the report.

**Comment by starpit** [comment] 2019-05-23 23:37
update: we have a few options right now, none ideal.

1) kill the electron process when the last window closes; the consequence of this is that users will not see any amortization of the costs of launching electron; this also won't address the problem of passing environment updates if you have a window already open.

2) stop using a single electron process; this will result in bloat (one full chromium per kui window)

3) use a self-managed mechanism for passing env var updates back to the main process; we can use the filesystem as a conduit for this, as long as we pay some care to concurrency issues

the self-managed part of 3 is necessitated by a gap in the current electron API; the `second-instance` event does not pass the environment variable map of the second process to the first (it *does* pass the second's commandLine and workingDirectory). see https://github.com/electron/electron/issues/18434

**Comment by starpit** [comment] 2022-04-15 00:01
/remove-lifecycle rotten

Electron finally has the support we need for this.

**Comment by starpit** [comment] 2022-09-08 14:49
This was fixed a while back in #8858 The fix should be live in the latest builds.

**Closed by starpit** 2022-09-08 14:49 UTC
Labels: kind/bug, lifecycle/rotten
