### ISSUE TITLE
On windows kubectl commands hang

### ISSUE THREAD

**Issue by cosminilie** [kubernetes-sigs/kui#9132] opened 2022-12-07 09:12 UTC
I've downlowd the latest version "20.3.1" on windows and it seems it has some issues with any kubernetes command. It's able to select the right context but it hangs tryting to pull the namespace. And any commands don't do anything they just stay in running for some time.

![image](https://user-images.githubusercontent.com/2363771/206136773-1045a181-ad61-4a42-b511-89e5b83c5a06.png)
 
Running commands like ls works.  The kubectl version is: 

```WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

Here is a debug log

```
2022-12-07T09:24:10.520Z main/main loading
2022-12-07T09:24:10.521Z main/main shortcut to graphics [ 'C:\\Program Files\\Kui-win32-x64\\Kui.exe' ]
2022-12-07T09:24:10.532Z main/spawn-electron loading
2022-12-07T09:24:10.532Z main/spawn-electron getCommand [ 'C:\\Program Files\\Kui-win32-x64\\Kui.exe' ]
2022-12-07T09:24:10.533Z main/spawn-electron isShell [] true
2022-12-07T09:24:10.533Z main/spawn-electron using args [ 'shell' ] {
  cwd: 'C:\\Users\\Cosmin Ilie',
  env: {
    ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
    PROMPT: '$P$G',
    __PSLockDownPolicy: '0',
    ALLUSERSPROFILE: 'C:\\ProgramData',
    APPDATA: 'C:\\Users\\Cosmin Ilie\\AppData\\Roaming',
    ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
    ChocolateyLastPathUpdate: '133148052718721228',
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'DESKTOP-XXXXXX',
    ComSpec: 'C:\\Windows\\system32\\cmd.exe',
    DEBUG: '*',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
    FPS_BROWSER_USER_PROFILE_STRING: 'Default',
    GIT_SSH: 'C:\\Windows\\System32\\OpenSSH\\ssh.exe',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\Cosmin Ilie',
    LOCALAPPDATA: 'C:\\Users\\Cosmin Ilie\\AppData\\Local',
    LOGONSERVER: '\\\\DESKTOP-XXXXXX',
    NUMBER_OF_PROCESSORS: '16',
    OneDrive: 'C:\\Users\\Cosmin Ilie\\OneDrive - YYYYYY',
    OneDriveCommercial: 'C:\\Users\\Cosmin Ilie\\OneDrive - YYYYYY',
    OS: 'Windows_NT',
    Path: 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\WindowsPowerShell\\Scripts;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\TortoiseGit\\bin;C:\\Program Files\\PowerShell\\7\\;C:\\Program Files\\Amazon\\AWSCLIV2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Kui-win32-x64;C:\\ProgramData\\personal-bin;C:\\Users\\Cosmin Ilie\\AppData\\Local\\Programs\\oh-my-posh\\bin;C:\\Users\\Cosmin Ilie\\.krew\\bin',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
    POSH_THEMES_PATH: 'C:\\Users\\Cosmin Ilie\\AppData\\Local\\Programs\\oh-my-posh\\themes',
    POWERSHELL_DISTRIBUTION_CHANNEL: 'MSI:Windows 10 Pro',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 141 Stepping 1, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: '8d01',
    ProgramData: 'C:\\ProgramData',
    ProgramFiles: 'C:\\Program Files',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    SystemDrive: 'C:',
    SystemRoot: 'C:\\Windows',
    TEMP: 'C:\\Users\\COSMIN~1\\AppData\\Local\\Temp',
    TMP: 'C:\\Users\\COSMIN~1\\AppData\\Local\\Temp',
    USERDOMAIN: 'DESKTOP-XXXXXX',
    USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-XXXXXX',
    USERNAME: 'Cosmin Ilie',
    USERPROFILE: 'C:\\Users\\Cosmin Ilie',
    windir: 'C:\\Windows',
    WSLENV: 'WT_SESSION::WT_PROFILE_ID',
    WT_PROFILE_ID: '{0caa0dad-35be-5f56-a8ff-afceeeaa6101}',
    WT_SESSION: 'b322ac69-a9ba-4b78-a571-7667e9000531',
    ZES_ENABLE_SYSMAN: '1'
  }
}
2022-12-07T09:24:10.535Z main/spawn-electron initElectron [ 'shell' ] false {
  cwd: 'C:\\Users\\Cosmin Ilie',
  env: {
    ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
    PROMPT: '$P$G',
    __PSLockDownPolicy: '0',
    ALLUSERSPROFILE: 'C:\\ProgramData',
    APPDATA: 'C:\\Users\\Cosmin Ilie\\AppData\\Roaming',
    ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
    ChocolateyLastPathUpdate: '133148052718721228',
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'DESKTOP-XXXXXX',
    ComSpec: 'C:\\Windows\\system32\\cmd.exe',
    DEBUG: '*',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
    FPS_BROWSER_USER_PROFILE_STRING: 'Default',
    GIT_SSH: 'C:\\Windows\\System32\\OpenSSH\\ssh.exe',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\Cosmin Ilie',
    LOCALAPPDATA: 'C:\\Users\\Cosmin Ilie\\AppData\\Local',
    LOGONSERVER: '\\\\DESKTOP-XXXXXX',
    NUMBER_OF_PROCESSORS: '16',
    OneDrive: 'C:\\Users\\Cosmin Ilie\\OneDrive - YYYYYY',
    OneDriveCommercial: 'C:\\Users\\Cosmin Ilie\\OneDrive - YYYYYY',
    OS: 'Windows_NT',
    Path: 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\WindowsPowerShell\\Scripts;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\TortoiseGit\\bin;C:\\Program Files\\PowerShell\\7\\;C:\\Program Files\\Amazon\\AWSCLIV2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Kui-win32-x64;C:\\ProgramData\\personal-bin;C:\\Users\\Cosmin Ilie\\AppData\\Local\\Programs\\oh-my-posh\\bin;C:\\Users\\Cosmin Ilie\\.krew\\bin',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
    POSH_THEMES_PATH: 'C:\\Users\\Cosmin Ilie\\AppData\\Local\\Programs\\oh-my-posh\\themes',
    POWERSHELL_DISTRIBUTION_CHANNEL: 'MSI:Windows 10 Pro',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 141 Stepping 1, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: '8d01',
    ProgramData: 'C:\\ProgramData',
    ProgramFiles: 'C:\\Program Files',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    SystemDrive: 'C:',
    SystemRoot: 'C:\\Windows',
    TEMP: 'C:\\Users\\COSMIN~1\\AppData\\Local\\Temp',
    TMP: 'C:\\Users\\COSMIN~1\\AppData\\Local\\Temp',
    USERDOMAIN: 'DESKTOP-XXXXXX',
    USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-XXXXXX',
    USERNAME: 'Cosmin Ilie',
    USERPROFILE: 'C:\\Users\\Cosmin Ilie',
    windir: 'C:\\Windows',
    WSLENV: 'WT_SESSION::WT_PROFILE_ID',
    WT_PROFILE_ID: '{0caa0dad-35be-5f56-a8ff-afceeeaa6101}',
    WT_SESSION: 'b322ac69-a9ba-4b78-a571-7667e9000531',
    ZES_ENABLE_SYSMAN: '1'
  }
}
2022-12-07T09:24:10.536Z main/spawn-electron loading electron
2022-12-07T09:24:10.536Z main/main isRunningHeadless false
2022-12-07T09:24:10.536Z main/main all done here, the rest is async
2022-12-07T09:24:10.583Z main/spawn-electron opening primary window [ 'shell' ]
2022-12-07T09:24:10.583Z main/spawn-electron createWindow [ 'shell' ]
2022-12-07T09:24:10.586Z main/spawn-electron createWindow::new BrowserWindow
2022-12-07T09:24:10.629Z main/spawn-electron createWindow::new BrowserWindow success
2022-12-07T09:24:10.629Z main/spawn-electron setting argv [ 'shell' ]
2022-12-07T09:24:10.630Z main/spawn-electron subwindowPrefs {
  cwd: 'C:\\Users\\Cosmin Ilie',
  env: {
    ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
    PROMPT: '$P$G',
    __PSLockDownPolicy: '0',
    ALLUSERSPROFILE: 'C:\\ProgramData',
    APPDATA: 'C:\\Users\\Cosmin Ilie\\AppData\\Roaming',
    ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
    ChocolateyLastPathUpdate: '133148052718721228',
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'DESKTOP-XXXXXX',
    ComSpec: 'C:\\Windows\\system32\\cmd.exe',
    DEBUG: '*',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
    FPS_BROWSER_USER_PROFILE_STRING: 'Default',
    GIT_SSH: 'C:\\Windows\\System32\\OpenSSH\\ssh.exe',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\Cosmin Ilie',
    LOCALAPPDATA: 'C:\\Users\\Cosmin Ilie\\AppData\\Local',
    LOGONSERVER: '\\\\DESKTOP-XXXXXX',
    NUMBER_OF_PROCESSORS: '16',
    OneDrive: 'C:\\Users\\Cosmin Ilie\\OneDrive - YYYYYY',
    OneDriveCommercial: 'C:\\Users\\Cosmin Ilie\\OneDrive - YYYYYY',
    OS: 'Windows_NT',
    Path: 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\WindowsPowerShell\\Scripts;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\TortoiseGit\\bin;C:\\Program Files\\PowerShell\\7\\;C:\\Program Files\\Amazon\\AWSCLIV2\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Kui-win32-x64;C:\\ProgramData\\personal-bin;C:\\Users\\Cosmin Ilie\\AppData\\Local\\Programs\\oh-my-posh\\bin;C:\\Users\\Cosmin Ilie\\.krew\\bin',
    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
    POSH_THEMES_PATH: 'C:\\Users\\Cosmin Ilie\\AppData\\Local\\Programs\\oh-my-posh\\themes',
    POWERSHELL_DISTRIBUTION_CHANNEL: 'MSI:Windows 10 Pro',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 141 Stepping 1, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: '8d01',
    ProgramData: 'C:\\ProgramData',
    ProgramFiles: 'C:\\Program Files',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    SystemDrive: 'C:',
    SystemRoot: 'C:\\Windows',
    TEMP: 'C:\\Users\\COSMIN~1\\AppData\\Local\\Temp',
    TMP: 'C:\\Users\\COSMIN~1\\AppData\\Local\\Temp',
    USERDOMAIN: 'DESKTOP-XXXXXX',
    USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-XXXXXX',
    USERNAME: 'Cosmin Ilie',
    USERPROFILE: 'C:\\Users\\Cosmin Ilie',
    windir: 'C:\\Windows',
    WSLENV: 'WT_SESSION::WT_PROFILE_ID',
    WT_PROFILE_ID: '{0caa0dad-35be-5f56-a8ff-afceeeaa6101}',
    WT_SESSION: 'b322ac69-a9ba-4b78-a571-7667e9000531',
    ZES_ENABLE_SYSMAN: '1'
  }
}
2022-12-07T09:24:10.630Z main/spawn-electron mainWindow::loadURL file:///C:\Program Files\Kui-win32-x64\resources\app\node_modules\@kui-shell\build\index.html
2022-12-07T09:24:10.639Z main/spawn-electron install menus
2022-12-07T09:24:10.641Z core/capabilities loading
2022-12-07T09:24:10.648Z core/usage-error loading
2022-12-07T09:24:10.652Z webapp/electron-events loading
2022-12-07T09:24:10.654Z main/spawn-electron ipc registration
2022-12-07T09:24:10.654Z main/spawn-electron createWindow done
2022-12-07T09:24:11.612Z main/spawn-electron invoke {
  module: 'plugin-kubectl-tray-menu',
  main: 'initTray',
  args: { command: '/tray/init' }
}
2022-12-07T09:24:11.613Z main/spawn-electron invoke got module
2022-12-07T09:24:11.616Z main/spawn-electron invoke got returnValue undefined
2022-12-07T09:24:11.637Z plugin-kubectl-tray-menu/main constructor
2022-12-07T09:24:11.837Z plugin-kubectl-tray-menu/main render
2022-12-07T09:24:11.838Z plugin-kubectl-tray-menu/context-watcher constructor
2022-12-07T09:24:11.838Z plugin-kubectl-tray-menu/namespace-watcher constructor
2022-12-07T09:24:11.844Z plugin-kubectl-tray-menu/context-watcher scan
2022-12-07T09:24:11.859Z plugin-kubectl-tray-menu/namespace-watcher scan
2022-12-07T09:24:12.084Z plugin-kubectl-tray-menu/context-watcher scan done false
2022-12-07T09:24:12.295Z plugin-kubectl-tray-menu/main render
2022-12-07T09:24:13.337Z plugin-kubectl-tray-menu/namespace-watcher findAndSetCurrentNamespace 4
2022-12-07T09:24:13.544Z plugin-kubectl-tray-menu/main render
2022-12-07T09:24:21.845Z plugin-kubectl-tray-menu/main render
2022-12-07T09:24:31.843Z plugin-kubectl-tray-menu/main render
2022-12-07T09:24:41.846Z plugin-kubectl-tray-menu/main render
2022-12-07T09:24:51.852Z plugin-kubectl-tray-menu/main render

```

**Comment by starpit** [comment] 2022-12-07 18:04
thanks for the bug report! are you on a) WSL2; b) powershell; c) git bash; d) other?

if you have a chance, can you open up the dev tools (View -> Toggle Developer Tools) and see if there are any errors in the Console?

thanks!

**Comment by cosminilie** [comment] 2022-12-08 08:23
Seems like i was able to find something in the console

```
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +0ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +20ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +53ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +51ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +52ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
53156.3fc17f1bb6a200c89ffe.bundle.js:1 Suspicious return value for current namespace true kubectl config view --minify --context rancher-desktop --output "jsonpath={..namespace}"
(anonymous) @ 53156.3fc17f1bb6a200c89ffe.bundle.js:1
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +63ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +64ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +61ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +60ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +52ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +52ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +0ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
33780.5b463f45261008792060.bundle.js:1 needle Making request #1 +53ms Object
33780.5b463f45261008792060.bundle.js:1 needle Request error +1ms Error: connect ECONNREFUSED 127.0.0.1:9000
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:643:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```

**Comment by n3wjack** [comment] 2023-03-26 11:57
I'm seeing the same issue on Windows on 13.1.3.
What I think is causing the issue is the fact that after closing Kui, the kubectl processes it starts in the background aren't killed. They keep hanging around if you look with task manager or process explorer (from sysinternals). When I kill them and restart Kui, I can run kubectrl commands again.

In the screenshots below you can see the state when Kui is running, and after it's closed.
The kubectl & conhost processes have the same PIDs, and aren't killed with the app.

![kui-process-info](https://user-images.githubusercontent.com/2250770/227773933-068edec5-5ab1-497c-869c-76ac5b3ab905.png)
![kui-hanging-kubctl-after-quiting](https://user-images.githubusercontent.com/2250770/227773934-98ae3b75-269e-46ff-85db-76c3b0ddbbd9.png)

**Closed** 2023-05-25 12:46 UTC
Labels: kind/bug, platform/windows, plugin-kubectl, lifecycle/rotten
